"""empty message

Revision ID: 0d84059804ab
Revises: 4c36552ffbfd
Create Date: 2022-12-16 09:30:21.678226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d84059804ab'
down_revision = '4c36552ffbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mandlebrot_frame')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandlebrot_frame',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start', sa.INTEGER(), nullable=False),
    sa.Column('end', sa.INTEGER(), nullable=False),
    sa.Column('speed', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['end'], ['mandlebrot.id'], ),
    sa.ForeignKeyConstraint(['start'], ['mandlebrot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
