"""empty message

Revision ID: 4c36552ffbfd
Revises: bc6d1ddcbc89
Create Date: 2022-12-15 23:31:43.092091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c36552ffbfd'
down_revision = 'bc6d1ddcbc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandlebrot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zoom', sa.Float(), nullable=True),
    sa.Column('focusx', sa.Float(precision=24), nullable=True),
    sa.Column('focusy', sa.Float(precision=24), nullable=True),
    sa.Column('iterations', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mandlebrot_frame',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['end'], ['mandlebrot.id'], ),
    sa.ForeignKeyConstraint(['start'], ['mandlebrot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mandlebrot_frame')
    op.drop_table('mandlebrot')
    # ### end Alembic commands ###
