"""empty message

Revision ID: 6d0b8d2deb04
Revises: 0d84059804ab
Create Date: 2022-12-16 09:41:41.220094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d0b8d2deb04'
down_revision = '0d84059804ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mandlebrot', schema=None) as batch_op:
        batch_op.alter_column('zoom',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('focusx',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('focusy',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('iterations',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('width',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mandlebrot', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('width',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('iterations',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('focusy',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('focusx',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('zoom',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
